package com.aasra.companion.care

internal class CareSpec(
    val pattern: Regex,
    val en: String,
    val hi: String,
    val urgent: Boolean,
    val enSteps: List<String>,
    val hiSteps: List<String>,
)

internal object CareCatalog {
    val all: List<CareSpec> = listOf(
        u("chest pain|heart attack|seenay|seene mein|सीने.{0,12}दर्द|दिल दर्द|heart pain", "chest pain", "सीने में दर्द",
            "Sit still. Do not walk. Loosen tight clothes.",
            "Tell someone nearby. Use SOS or local emergency services now.",
            "If your doctor already gave you a heart tablet for this, take only that, as they taught you.",
            "Stay sitting until help arrives.",
            "बैठे रहें। चलें नहीं। तंग कपड़े ढीले करें।",
            "पास वाले को बताएँ। अभी एसओएस या आपातकालीन सेवा।",
            "डॉक्टर ने दिल की गोली दी हो तो केवल वही, जैसा उन्होंने कहा।",
            "मदद आने तक बैठे रहें।"),
        u("can'?t breathe|cannot breathe|shortness of breath|breathless|saans nahi|saans phool|सांस नहीं|साँस नहीं|सांस फूल", "hard to breathe", "साँस में तकलीफ",
            "Sit upright. Open a window. Loosen the collar.",
            "Breathe in slowly through the nose, out through the mouth.",
            "Use SOS if breathing stays hard or lips look blue.",
            "If you have an inhaler your doctor gave you, use it the way they taught you.",
            "सीधे बैठें। खिड़की खोलें। कॉलर ढीला करें।",
            "नाक से धीरे साँस लें, मुँह से छोड़ें।",
            "साँस कठिन रहे या होंठ नीले लगें तो एसओएस।",
            "डॉक्टर वाला इनहेलर हो तो उसी तरह लें जैसे उन्होंने बताया।"),
        u("stroke|slurred speech|face droop|one side weak|एक तरफ़ कमज़ोर|बोली लड़खड़|मुँह टेढ़", "stroke signs", "लकवे जैसे लक्षण",
            "Note the time. Do not give food or water.",
            "Use SOS or local emergency services now.",
            "Help them sit or lie with the head a little raised.",
            "Stay with them until help arrives.",
            "समय देख लें। खाना-पानी न दें।",
            "अभी एसओएस या आपातकालीन सेवा।",
            "सिर थोड़ा ऊँचा रखकर बैठाएँ या लिटाएँ।",
            "मदद आने तक साथ रहें।"),
        u("unconscious|passed out|behosh|बेहोश|बेहोशी", "unconscious", "बेहोशी",
            "Call out. Use SOS. Check if they are breathing.",
            "If breathing, roll them onto their side.",
            "Do not give food, water, or tablets.",
            "Stay until help arrives.",
            "आवाज़ दें। एसओएस दबाएँ। साँस देखें।",
            "साँस आ रही हो तो करवट पर लिटाएँ।",
            "खाना, पानी, गोली न दें।",
            "मदद आने तक साथ रहें।"),
        u("choke|choking|food stuck in throat|गले में अटका|दम घुट", "choking", "गला अटकना",
            "If they can cough, let them cough. Do not slap the back if they can speak.",
            "If they cannot breathe or speak, use SOS and call for help.",
            "Bend them forward and give firm back blows between the shoulders.",
            "Do not put fingers blindly into the mouth.",
            "खाँस सकते हैं तो खाँसने दें। बोल सकते हैं तो पीठ न पीटें।",
            "साँस या आवाज़ न आए तो एसओएस।",
            "आगे झुकाएँ, कंधों के बीच पीठ पर ज़ोर से थपकी दें।",
            "मुँह में अंधाधुंध उंगली न डालें।"),
        u("heavy bleed|bleeding (a lot|lots)|khoon bah|खून बह|बहुत खून", "heavy bleeding", "तेज़ खून बहना",
            "Sit or lie down. Press the wound firmly with a clean cloth.",
            "Keep pressing. Raise the part if you can.",
            "Use SOS if blood soaks the cloth or will not slow.",
            "Do not pull out a deep object. Press around it.",
            "बैठें या लेटें। साफ़ कपड़े से घाव दबाएँ।",
            "दबाए रखें। हो सके तो वह हिस्सा ऊँचा करें।",
            "कपड़ा भीग जाए या खून न रुके तो एसओएस।",
            "गड़ी चीज़ न निकालें। उसके आसपास दबाएँ।"),
        u("seizure|fit |fits |ainthee|दौरा|ऐंठन", "seizure", "दौरा",
            "Clear hard objects. Cushion the head. Do not hold them down.",
            "Do not put anything in the mouth.",
            "After it stops, roll them onto their side. Use SOS if it lasts or they do not wake.",
            "Stay until they are fully awake.",
            "कड़ी चीज़ें हटाएँ। सिर के नीचे कपड़ा दें। पकड़कर न रोकें।",
            "मुँह में कुछ न डालें।",
            "रुकने पर करवट लिटाएँ। लंबा रहे या न जगें तो एसओएस।",
            "पूरी तरह जागने तक साथ रहें।"),
        u("swell(en|ing)? (lip|tongue|throat)|anaphylaxis|hives all|जीभ फूल|होंठ फूल|गला सूज", "swelling of lips or tongue", "होंठ या जीभ सूजन",
            "Use SOS now. This can close the throat.",
            "Sit upright. Loosen the collar.",
            "If a doctor already gave you an emergency pen for this, use it as they taught you.",
            "Do not lie flat if breathing is hard.",
            "अभी एसओएस। गला बंद हो सकता है।",
            "सीधे बैठें। कॉलर ढीला करें।",
            "डॉक्टर ने आपातकालीन पेन दी हो तो उसी तरह लगाएँ।",
            "साँस कठिन हो तो चित लेटकर न रहें।"),
        u("vomit(ing)? blood|blood in vomit|खून की उल्टी|उल्टी में खून", "blood in vomit", "उल्टी में खून",
            "Sit up. Do not eat or drink.",
            "Use SOS or go to emergency care now.",
            "Keep a bowl. Note the colour if you can.",
            "Stay still until help arrives.",
            "बैठे रहें। खाना-पानी न लें।",
            "अभी एसओएस या अस्पताल।",
            "बर्तन रखें। रंग याद रखें।",
            "मदद तक शांत रहें।"),
        u("cough(ing)? blood|blood in (cough|phlegm|spit)|खांसी में खून|खाँसी में खून|थूक में खून", "blood in cough", "खाँसी में खून",
            "Sit upright. Spit into a cloth. Do not lie flat.",
            "Use SOS if there is a lot of blood or breathing is hard.",
            "Call a doctor the same day even if it is a little.",
            "Do not take a new cough medicine on your own.",
            "सीधे बैठें। कपड़े में थूकें। चित न लेटें।",
            "ज़्यादा खून या साँस कठिन हो तो एसओएस।",
            "थोड़ा भी हो तो उसी दिन डॉक्टर को बताएँ।",
            "नई खाँसी की दवाई खुद से न लें।"),
        u("worst headache|sudden (severe|strong) headache|thunderclap|अचानक तेज़ सिर", "sudden severe headache", "अचानक तेज़ सिर दर्द",
            "Sit or lie in a dark room. Do not drive.",
            "Use SOS if this is the worst pain of your life, or you vomit, or the neck is stiff.",
            "Tell family the time it started.",
            "Do not take a new tablet unless a doctor already said so.",
            "अंधेरे कमरे में बैठें। गाड़ी न चलाएँ।",
            "जीवन का सबसे तेज़ दर्द, उल्टी, या गर्दन अकड़न हो तो एसओएस।",
            "परिवार को शुरू होने का समय बताएँ।",
            "नई गोली न लें जब तक डॉक्टर ने न कहा हो।"),
        u("stiff neck.{0,20}fever|fever.{0,20}stiff neck|गर्दन अकड़.{0,16}बुखार|बुखार.{0,16}गर्दन", "fever with stiff neck", "बुखार और गर्दन अकड़न",
            "Lie still. Do not force the neck.",
            "Use SOS or see emergency care now.",
            "Sip water if you can swallow easily.",
            "Tell them about the fever and the stiff neck.",
            "लेटे रहें। गर्दन ज़बरदस्ती न घुमाएँ।",
            "अभी एसओएस या अस्पताल।",
            "निगल आसान हो तो पानी पिएँ।",
            "बुखार और गर्दन अकड़न दोनों बताएँ।"),
        u("one leg (swell|swollen)|ek tang sooj|एक टांग सूज|एक पैर सूज", "one leg swollen", "एक टांग सूजी",
            "Sit with that leg raised. Do not massage it.",
            "Use SOS if the leg is hot, red, or you also have chest pain or hard breathing.",
            "Call a doctor the same day.",
            "Do not walk far on it.",
            "वह टांग ऊँची करके बैठें। मसाज न करें।",
            "गरम, लाल, या साथ में सीने/साँस की तकलीफ हो तो एसओएस।",
            "उसी दिन डॉक्टर को दिखाएँ।",
            "उस पर दूर न चलें।"),
        u("poison|swallowed (detergent|phenyl|kerosene)|ज़हर|फिनाइल पी|मिट्टी का तेल", "swallowed poison", "ज़हर या गलत चीज़ निगलना",
            "Use SOS. Take the bottle with you if you can.",
            "Do not make yourself vomit unless a doctor says so.",
            "Do not drink milk or oil on your own.",
            "Stay sitting. Tell them exactly what was swallowed.",
            "एसओएस करें। बोतल साथ ले जाएँ।",
            "डॉक्टर कहे बिना उल्टी न करवाएँ।",
            "दूध या तेल खुद से न पिएँ।",
            "बैठे रहें। क्या निगला बताया।"),
        u("snake bite|saanp|साँप काट", "snake bite", "साँप काटना",
            "Sit still. Keep the bitten part still and a little below the heart.",
            "Use SOS now. Do not cut, suck, or tie a tight tourniquet.",
            "Remove rings or tight bands near the bite.",
            "Note the time and, if safe, the snake’s look.",
            "बैठे रहें। काटी जगह शांत रखें, दिल से थोड़ी नीचे।",
            "अभी एसओएस। काटें नहीं, चूसें नहीं, बहुत कसकर न बाँधें।",
            "पास की अंगूठी-पट्टी निकालें।",
            "समय और साँप का रंग-रूप याद रखें।"),
        u("dog bite|kutte ne|कुत्ते ने काट", "dog bite", "कुत्ते का काटना",
            "Wash the wound with soap and running water for several minutes.",
            "Cover with a clean cloth. See a doctor the same day for rabies advice.",
            "Do not put mud, oil, or turmeric on it.",
            "If the dog is unknown or the wound is deep, go sooner.",
            "साबुन और बहते पानी से कई मिनट धोएँ।",
            "साफ़ कपड़ा बाँधें। रेबीज़ के लिए उसी दिन डॉक्टर।",
            "मिट्टी, तेल, हल्दी न लगाएँ।",
            "अजनबी कुत्ता या गहरा घाव हो तो जल्दी जाएँ।"),
        u("head (hit|injury)|hit my head|सर लग|सिर लग|सिर में चोट", "head injury", "सिर में चोट",
            "Sit or lie still. Use SOS if they faint, vomit, or talk strangely.",
            "A cold cloth on the bump can help. Do not press a deep wound hard.",
            "Stay with someone for the next hours.",
            "See a doctor after any fall that hits the head, even if you feel fine now.",
            "बैठे या लेटे रहें। बेहोशी, उल्टी, या अजीब बात हो तो एसओएस।",
            "सूजन पर ठंडा कपड़ा। गहरे घाव को ज़ोर से न दबाएँ।",
            "कुछ घंटे किसी के साथ रहें।",
            "सिर लगा हो तो अच्छा लगने पर भी डॉक्टर दिखाएँ।"),

        n("low sugar|hypogly|sugar (gir|low|giri)|शुगर गिर|शुगर लो|मिठा कम", "low sugar", "शुगर गिरना",
            "Sit down. If you can swallow, take a sweet drink or glucose your doctor already advised.",
            "Do not drive. Tell family.",
            "Check sugar the way your doctor taught you, if you can.",
            "Use SOS if you feel faint, confused, or cannot swallow.",
            "बैठ जाएँ। निगल सकते हैं तो डॉक्टर वाला मीठा पेय या ग्लूकोज़ लें।",
            "गाड़ी न चलाएँ। परिवार को बताएँ।",
            "हो सके तो डॉक्टर के तरीके से शुगर देखें।",
            "बेहोशी, उलझन, या निगल न सकें तो एसओएस।"),
        n("high sugar|sugar (high|chad)|शुगर हाई|शुगर चढ़", "high sugar feeling", "शुगर चढ़ना",
            "Sip water. Rest. Do not take extra insulin or tablets on your own.",
            "Check sugar the way your doctor taught you.",
            "Call your doctor if you vomit, breathe very fast, or feel very sleepy.",
            "Tell family. Keep your usual meal plan unless the doctor said otherwise.",
            "पानी पिएँ। आराम करें। खुद से अतिरिक्त इंसुलिन या गोली न लें।",
            "डॉक्टर के तरीके से शुगर देखें।",
            "उल्टी, बहुत तेज़ साँस, या बहुत नींद आए तो डॉक्टर को फोन करें।",
            "परिवार को बताएँ। खाने का तरीका डॉक्टर की सलाह के बिना न बदलें।"),
        n("bp high|high bp|blood pressure high|बीपी हाई|बीपी चढ़|high blood", "high BP feeling", "बीपी चढ़ना",
            "Sit quietly. Rest the arm. Breathe slowly.",
            "Take only BP medicine your doctor already gave you, at the usual time. Do not take an extra tablet on your own.",
            "Call a doctor if you also have chest pain, hard breathing, or a sudden bad headache.",
            "Avoid extra salt and heavy work until you have spoken to your doctor.",
            "शांत बैठें। बाजू आराम दें। धीरे साँस लें।",
            "केवल डॉक्टर वाली बीपी की दवाई, उसी समय। अतिरिक्त गोली खुद से न लें।",
            "साथ में सीने में दर्द, साँस, या अचानक तेज़ सिर दर्द हो तो डॉक्टर।",
            "डॉक्टर से बात होने तक ज़्यादा नमक और भारी काम न करें।"),
        n("bp low|low bp|blood pressure low|बीपी लो|बीपी गिर", "low BP feeling", "बीपी गिरना",
            "Lie down and raise the legs a little if you can.",
            "Sip water. Sit up slowly later.",
            "Do not stand quickly. Ask someone to stay.",
            "Call a doctor if you faint, the chest hurts, or this keeps happening.",
            "लेटें, हो सके तो पैर थोड़े ऊँचे करें।",
            "पानी पिएँ। बाद में धीरे बैठें।",
            "जल्दी न उठें। किसी को पास रखें।",
            "बेहोशी, सीने में दर्द, या बार-बार हो तो डॉक्टर।"),
        n("palpitation|heart rac|dhadkan|धड़कन|दिल तेज़", "fast heartbeat", "तेज़ धड़कन",
            "Sit. Loosen tight clothes. Breathe slowly.",
            "Sip water. Rest.",
            "Call a doctor if it lasts, you faint, or the chest also hurts.",
            "Do not take a new heart tablet on your own.",
            "बैठें। कपड़े ढीले करें। धीरे साँस लें।",
            "पानी पिएँ। आराम करें।",
            "बना रहे, बेहोशी, या सीने में दर्द हो तो डॉक्टर।",
            "नई दिल की गोली खुद से न लें।"),
        n("wheez|dama |asthma|दमा|घरघराहट", "wheeze or asthma", "घरघराहट या दमा",
            "Sit upright. Use the inhaler your doctor already gave you, as they taught you.",
            "Stay calm. Open a window. Loosen the collar.",
            "Use SOS if the inhaler does not help or lips look blue.",
            "Avoid smoke and dust right now.",
            "सीधे बैठें। डॉक्टर वाला इनहेलर उसी तरह लें जैसे बताया।",
            "शांत रहें। खिड़की खोलें। कॉलर ढीला करें।",
            "इनहेलर से राहत न मिले या होंठ नीले लगें तो एसओएस।",
            "अभी धुआँ और धूल से दूर रहें।"),
        n("fev+e?r|feaver|bukh+a+r|बुखार|ताप चढ़", "fever", "बुखार",
            "Lie in a cool room. Loosen clothes.",
            "Sip water often. A lukewarm cloth on the forehead can help.",
            "Take only fever medicine your doctor already gave you, as they told you.",
            "Call a doctor if fever lasts more than two days, you feel confused, or breathing is hard.",
            "ठंडे कमरे में लेटें। कपड़े ढीले करें।",
            "थोड़ा-थोड़ा पानी पिएँ। माथे पर गुनगुना कपड़ा रखें।",
            "केवल डॉक्टर वाली बुखार की दवाई, जैसा उन्होंने कहा।",
            "दो दिन से ज़्यादा, उलझन, या साँस कठिन हो तो डॉक्टर।"),
        n("chills|thandi lag|काँप|ठंड लग|shiver", "chills", "ठंड लगना",
            "Cover with a light sheet, not too many heavy blankets.",
            "Sip warm water. Rest.",
            "If you also have fever, follow your fever card and tell family.",
            "Call a doctor if chills are strong or you cannot get warm.",
            "हल्की चादर ओढ़ें, बहुत भारी रजाई न लादें।",
            "गुनगुना पानी पिएँ। आराम करें।",
            "साथ में बुखार हो तो परिवार को बताएँ।",
            "बहुत तेज़ काँप या गर्मी न आए तो डॉक्टर।"),
        n("dry cough|sukhi khansi|सूखी खाँसी|सूखी खांसी", "dry cough", "सूखी खाँसी",
            "Sit up. Sip warm water slowly. Rest your voice.",
            "A little steam from hot water can help if it feels easy. Keep the face away from the water.",
            "Stay away from smoke and dust.",
            "Call a doctor if it lasts many days, there is blood, or nights are very bad.",
            "बैठकर गुनगुना पानी पिएँ। आवाज़ आराम दें।",
            "आसान लगे तो भाप लें। चेहरा पानी से दूर रखें।",
            "धुआँ-धूल से दूर रहें।",
            "कई दिन, खून, या रात बहुत खराब हो तो डॉक्टर।"),
        n("phlegm|wet cough|balgam|कफ|बलगम|गीली खाँसी", "cough with phlegm", "कफ वाली खाँसी",
            "Sit up. Sip warm water. Spit phlegm into a cloth. Do not swallow a lot of it.",
            "Breathe steam if it feels easy.",
            "Do not take a new cough syrup on your own.",
            "Call a doctor if phlegm is yellow-green for days, there is blood, or breathing is hard.",
            "बैठकर गुनगुना पानी पिएँ। कफ कपड़े में थूकें।",
            "आसान लगे तो भाप लें।",
            "नई खाँसी की सिरप खुद से न लें।",
            "कई दिन पीला-हरा कफ, खून, या साँस कठिन हो तो डॉक्टर।"),
        n("night cough|raat (ko )?khansi|रात.{0,8}खाँसी", "night cough", "रात की खाँसी",
            "Sleep with the head a little raised on extra pillows.",
            "Sip warm water before lying down.",
            "Avoid lying flat after a meal.",
            "Call a doctor if you wake often, wheeze, or have fever too.",
            "सिर थोड़ा ऊँचा करके सोएँ।",
            "लेटने से पहले गुनगुना पानी पिएँ।",
            "खाने के तुरंत बाद चित न लेटें।",
            "बार-बार जागें, घरघराहट, या बुखार हो तो डॉक्टर।"),
        n("cough|khans[iey]|खाँसी|खांसी", "cough", "खाँसी",
            "Sit upright. Sip warm water.",
            "Rest your voice. Steam if it feels easy.",
            "Stay away from smoke.",
            "Call a doctor if it lasts, there is blood, or you cannot catch your breath.",
            "सीधे बैठें। गुनगुना पानी पिएँ।",
            "आवाज़ आराम दें। आसान लगे तो भाप।",
            "धुआँ से दूर रहें।",
            "बनी रहे, खून आए, या साँस न आए तो डॉक्टर।"),
        n("\\bflu\\b|viral|वायरल|फ्लू", "flu-like illness", "वायरल जैसा बुखार",
            "Rest in bed. Sip water or soup often.",
            "A lukewarm cloth can help if you feel hot.",
            "Take only medicine your doctor already gave you for fever or body ache.",
            "Call a doctor if breathing is hard, you feel very weak, or this lasts.",
            "बिस्तर पर आराम। पानी या सूप पिएँ।",
            "गर्मी लगे तो गुनगुना कपड़ा।",
            "केवल डॉक्टर वाली बुखार/दर्द की दवाई।",
            "साँस कठिन, बहुत कमज़ोरी, या बना रहे तो डॉक्टर।"),
        n("\\bcold\\b|sardi|zukam|सर्दी|जुकाम", "cold", "सर्दी-जुकाम",
            "Rest. Keep warm, not sweaty.",
            "Drink water or warm fluids.",
            "Blow the nose gently. Sleep with the head raised.",
            "Call a doctor if fever is high or the face is very painful.",
            "आराम करें। गरम रहें, पसीना न आने दें।",
            "पानी या गुनगुना पेय पिएँ।",
            "नाक धीरे साफ़ करें। सिर ऊँचा करके सोएँ।",
            "तेज़ बुखार या चेहरे में बहुत दर्द हो तो डॉक्टर।"),
        n("sneeze|chheenk|छींक", "sneezing", "छींक",
            "Sit. Cover the sneeze with a cloth.",
            "Sip water. Stay away from dust and strong smells.",
            "A clean cloth on the nose can help.",
            "Call a doctor if sneezing comes with hard breathing or a rash.",
            "बैठें। कपड़े से छींक ढकें।",
            "पानी पिएँ। धूल और तेज़ गंध से दूर रहें।",
            "नाक पर साफ़ कपड़ा रख सकते हैं।",
            "साथ में साँस कठिन या दाने हों तो डॉक्टर।"),
        n("blocked nose|nak band|नाक बंद|nasal congest", "blocked nose", "नाक बंद",
            "Sit. Lean over a bowl of hot water and breathe steam if it feels easy.",
            "Sleep with the head raised. Sip warm water.",
            "Do not poke the nose with a stick.",
            "Call a doctor if this lasts many days or you have high fever.",
            "गर्म पानी की भाप लें अगर आसान लगे।",
            "सिर ऊँचा करके सोएँ। गुनगुना पानी पिएँ।",
            "नाक में कड़ी चीज़ न डालें।",
            "कई दिन या तेज़ बुखार हो तो डॉक्टर।"),
        n("runny nose|nak bah|नाक बह|रेनकी", "runny nose", "नाक बहना",
            "Blow gently, one side at a time. Keep a soft cloth.",
            "Sip warm water. Rest.",
            "Sleep with the head a little raised.",
            "Call a doctor if the face hurts a lot or fever is high.",
            "एक तरफ़ धीरे साफ़ करें। नरम कपड़ा रखें।",
            "गुनगुना पानी पिएँ। आराम करें।",
            "सिर थोड़ा ऊँचा करके सोएँ।",
            "चेहरे में बहुत दर्द या तेज़ बुखार हो तो डॉक्टर।"),
        n("sinus|saunas|साइनस", "sinus pain", "साइनस दर्द",
            "Steam the face if it feels easy. A warm cloth on the cheeks can help.",
            "Sip water. Rest the head raised.",
            "Do not poke the nose.",
            "Call a doctor if pain is strong, fever is high, or vision changes.",
            "आसान लगे तो भाप। गालों पर गुनगुना कपड़ा।",
            "पानी पिएँ। सिर ऊँचा रखकर आराम।",
            "नाक में कुछ न डालें।",
            "तेज़ दर्द, बुखार, या दिखना बदले तो डॉक्टर।"),
        n("sore throat|gale mein dard|गले में दर्द|गला दुख", "sore throat", "गले में दर्द",
            "Rinse with lukewarm water. Sip water slowly.",
            "Rest your voice. Avoid smoke and spicy food.",
            "Do not take a new antibiotic on your own.",
            "Call a doctor if swallowing is very painful, breathing is hard, or fever is high.",
            "गुनगुने पानी से कुल्ला। धीरे पानी पिएँ।",
            "आवाज़ आराम। धुआँ और तीखा खाना न लें।",
            "नई एंटीबायोटिक खुद से न लें।",
            "निगलना बहुत दर्द, साँस कठिन, या तेज़ बुखार हो तो डॉक्टर।"),
        n("hoarse|awaz baith|आवाज़ बैठ|गला बैठ", "hoarse voice", "आवाज़ बैठना",
            "Speak little. Sip warm water.",
            "Avoid shouting, smoke, and cold drinks.",
            "Rest the throat for a day.",
            "See a doctor if the voice stays gone more than a week or breathing is hard.",
            "कम बोलें। गुनगुना पानी पिएँ।",
            "चिल्लाएँ नहीं, धुआँ और ठंडा पेय न लें।",
            "एक दिन गले को आराम दें।",
            "एक सप्ताह से ज़्यादा या साँस कठिन हो तो डॉक्टर।"),
        n("migraine|माइग्रेन", "migraine", "माइग्रेन",
            "Lie in a dark, quiet room. Close the eyes.",
            "A cool cloth on the forehead or neck can help.",
            "Take only the migraine medicine your doctor already gave you.",
            "Call a doctor if this is new, much stronger, or one side of the body feels weak.",
            "अंधेरे शांत कमरे में लेटें। आँखें बंद करें।",
            "माथे या गर्दन पर ठंडा कपड़ा।",
            "केवल डॉक्टर वाली माइग्रेन की दवाई।",
            "नई, बहुत तेज़, या एक तरफ़ कमज़ोरी हो तो डॉक्टर।"),
        n("head.?ache|sar.{0,10}dard|sir.{0,10}dard|सिर.{0,10}दर्द|सर.{0,10}दर्द", "headache", "सिर दर्द",
            "Sit in a dim room. Close the eyes. Drink a glass of water.",
            "Eat a little if you have not eaten. A cool cloth on the forehead can help.",
            "Do not take a new pain tablet unless your doctor already said so.",
            "Call a doctor or use SOS if the pain is sudden and very strong, you vomit, or one side feels weak.",
            "कम रोशनी में बैठें। आँखें बंद करें। पानी पिएँ।",
            "भूख हो तो थोड़ा खाएँ। माथे पर ठंडा कपड़ा।",
            "नई दर्द की गोली न लें जब तक डॉक्टर ने न कहा हो।",
            "अचानक बहुत तेज़ दर्द, उल्टी, या एक तरफ़ कमज़ोरी हो तो डॉक्टर या एसओएस।"),
        n("eye strain|aankh thak|आँख थक|स्क्रीन", "eye strain", "आँख थकना",
            "Look away from the screen or book. Close the eyes for a few minutes.",
            "Blink slowly. Sit farther from bright light.",
            "A clean cool cloth on closed eyes can help.",
            "See a doctor if vision stays blurry or pain is strong.",
            "स्क्रीन से आँख हटाएँ। कुछ मिनट आँखें बंद करें।",
            "धीरे पलकें झपकाएँ। तेज़ रोशनी से दूर बैठें।",
            "बंद आँखों पर साफ़ ठंडा कपड़ा।",
            "धुंधला दिखे या दर्द तेज़ हो तो डॉक्टर।"),
        n("acidity|acid reflux|heartburn|jalan pet|एसिडिटी|सीने में जलन|हृदयदाह", "acidity", "एसिडिटी",
            "Sit up. Do not lie flat after eating.",
            "Sip a little cool water. Skip spicy, oily, and tea or coffee for now.",
            "Take only the acidity medicine your doctor already gave you.",
            "Call a doctor if you also have chest pain, vomit blood, or food sticks.",
            "बैठे रहें। खाने के बाद चित न लेटें।",
            "थोड़ा ठंडा पानी। तीखा, तैलीय, चाय-कॉफ़ी अभी न लें।",
            "केवल डॉक्टर वाली एसिडिटी की दवाई।",
            "साथ में सीने में दर्द, खून की उल्टी, या खाना अटके तो डॉक्टर।"),
        n("gas |gassy|bloating|pet phool|पेट फूल|गैस", "gas", "गैस-पेट फूलना",
            "Walk slowly in the room. Loosen the belt.",
            "Sip warm water. Skip beans, fried food, and soda for now.",
            "Do not take a new digestive tablet unless your doctor already said so.",
            "Call a doctor if the belly is hard, pain is severe, or you vomit a lot.",
            "कमरे में धीरे चलें। बेल्ट ढीली करें।",
            "गुनगुना पानी। दाल भारी, तला, ठंडा पेय अभी न लें।",
            "नई पचने की गोली न लें जब तक डॉक्टर ने न कहा हो।",
            "पेट सख्त, तेज़ दर्द, या ज़्यादा उल्टी हो तो डॉक्टर।"),
        n("indigestion|pet kharab|अपच|हज़म नहीं", "indigestion", "अपच",
            "Rest sitting. Eat a little plain food later, not more heavy food now.",
            "Sip warm water.",
            "Skip spicy and oily meals today.",
            "Call a doctor if pain is strong or you keep vomiting.",
            "बैठकर आराम। बाद में थोड़ा सादा खाना, अभी भारी नहीं।",
            "गुनगुना पानी पिएँ।",
            "आज तीखा-तैलीय न खाएँ।",
            "तेज़ दर्द या उल्टी बनी रहे तो डॉक्टर।"),
        n("food poison|sada khana|खाना खराब|फूड पॉइज़न", "food poisoning", "खराब खाना",
            "Sip water often, a little at a time. Rest near a toilet.",
            "Skip food until vomiting eases, then try a little plain rice or banana.",
            "Do not take a new antibiotic on your own.",
            "Call a doctor if there is blood, high fever, or you cannot keep water down.",
            "थोड़ा-थोड़ा पानी बार-बार। शौचालय के पास आराम।",
            "उल्टी रुकने तक खाना छोड़ें, फिर थोड़ा भात या केला।",
            "नई एंटीबायोटिक खुद से न लें।",
            "खून, तेज़ बुखार, या पानी न रुके तो डॉक्टर।"),
        n("nause|jee mich|जी मिचल|मतली", "nausea", "मतली",
            "Sit still. Breathe slowly. Sip water.",
            "Avoid cooking smells and oily food.",
            "Try a little dry biscuit if it stays down.",
            "Call a doctor if you cannot keep water down or you vomit blood.",
            "शांत बैठें। धीरे साँस। पानी पिएँ।",
            "रसोई की गंध और तैलीय खाना न लें।",
            "रुकता हो तो थोड़ा सूखा बिस्किट।",
            "पानी न रुके या खून आए तो डॉक्टर।"),
        n("vomit|throw up|ulti|उल्टी", "vomiting", "उल्टी",
            "Sit up. Rinse the mouth. Wait, then sip water slowly.",
            "Skip food until the stomach settles, then a little plain food.",
            "Do not gulp water.",
            "Call a doctor if it does not stop, there is blood, or you feel very weak.",
            "बैठें। मुँह धोएँ। बाद में धीरे पानी पिएँ।",
            "पेट शांत होने तक खाना छोड़ें, फिर सादा खाना।",
            "एक साथ ज़्यादा पानी न पिएँ।",
            "न रुके, खून आए, या बहुत कमज़ोरी हो तो डॉक्टर।"),
        n("constipat|kabz|कब्ज", "constipation", "कब्ज",
            "Drink more water through the day. Walk a little if you can.",
            "Eat fruit or the fibre food your doctor already allowed.",
            "Do not strain hard. Do not take a new laxative unless your doctor already said so.",
            "Call a doctor if there is blood, severe pain, or no stool for many days.",
            "दिन भर पानी पिएँ। हो सके तो थोड़ा चलें।",
            "फल या डॉक्टर वाली रेशेदार चीज़।",
            "ज़ोर न लगाएँ। नई जुलाब की दवाई खुद से न लें।",
            "खून, तेज़ दर्द, या कई दिन न हो तो डॉक्टर।"),
        n("diarrh|loose motion|dast|दस्त|पतला पेट", "loose motion", "दस्त",
            "Sip water or ORS often. Rest near a toilet.",
            "Eat light food when you can. Avoid raw, oily, or very sweet food.",
            "Do not take a new stop-loose tablet unless your doctor already said so.",
            "Call a doctor if there is blood, high fever, or this lasts more than a day.",
            "पानी या ओआरएस बार-बार पिएँ। शौचालय के पास रहें।",
            "हल्का खाना। कच्चा, तैलीय, बहुत मीठा न खाएँ।",
            "नई दस्त रोकने की गोली खुद से न लें।",
            "खून, तेज़ बुखार, या एक दिन से ज़्यादा हो तो डॉक्टर।"),
        n("piles|bawaseer|बवासीर", "piles", "बवासीर",
            "Sit in lukewarm water for a few minutes if you can get up safely.",
            "Drink water. Do not strain on the toilet. Eat fibre your doctor allowed.",
            "A clean soft cloth, not rough paper, after the toilet.",
            "See a doctor if there is a lot of blood or pain is severe.",
            "हो सके तो गुनगुने पानी में थोड़ी देर बैठें।",
            "पानी पिएँ। शौच पर ज़ोर न लगाएँ।",
            "कड़े कागज़ की जगह नरम साफ़ कपड़ा।",
            "ज़्यादा खून या तेज़ दर्द हो तो डॉक्टर।"),
        n("stomach|tummy|belly ache|pet.{0,10}dard|पेट.{0,10}दर्द|पेट दर्द", "stomach pain", "पेट दर्द",
            "Sit or lie with the knees bent. Loosen the belt.",
            "Sip water. Skip spicy, oily, and heavy food.",
            "Do not take a new pain tablet unless your doctor already said so.",
            "Call a doctor if pain is severe, the belly is hard, or there is blood.",
            "घुटने मोड़कर बैठें या लेटें। बेल्ट ढीली करें।",
            "पानी पिएँ। तीखा, तैलीय, भारी खाना न लें।",
            "नई दर्द की गोली न लें जब तक डॉक्टर ने न कहा हो।",
            "बहुत तेज़ दर्द, पेट सख्त, या खून हो तो डॉक्टर।"),
        n("kidney stone|pathri|पथरी", "stone pain", "पथरी का दर्द",
            "Sip water if your doctor already said you may. Walk slowly if you can.",
            "A warm cloth on the back can ease the ache.",
            "Take only pain medicine your doctor already gave you for this.",
            "Use SOS or go to hospital if pain is unbearable, you vomit a lot, or you see blood and cannot pass urine.",
            "डॉक्टर ने कहा हो तो पानी पिएँ। धीरे चलें।",
            "पीठ पर गुनगुना कपड़ा।",
            "केवल डॉक्टर वाली दर्द की दवाई।",
            "असहनीय दर्द, ज़्यादा उल्टी, या पेशाब न आए और खून हो तो अस्पताल।"),
        n("overeat|zyada kha|ज़्यादा खा|पेट भारी", "overeating", "ज़्यादा खाना",
            "Sit up. Loosen the belt. Walk a few slow steps.",
            "Sip warm water. Do not lie flat yet.",
            "Skip the next heavy snack. No new digestive tablet unless your doctor said so.",
            "Call a doctor if you have chest pain or hard breathing.",
            "बैठें। बेल्ट ढीली। धीरे कुछ कदम चलें।",
            "गुनगुना पानी। अभी चित न लेटें।",
            "अगला भारी नाश्ता छोड़ें।",
            "सीने में दर्द या साँस कठिन हो तो डॉक्टर।"),
        n("spicy food|teekha|तीखा लग|मिर्च", "spicy food upset", "तीखे खाने से तकलीफ",
            "Sip cool water or curd if you usually eat it.",
            "Skip more chilli today. Eat a little plain food later.",
            "Sit up. Do not lie flat soon after.",
            "Call a doctor if there is blood or severe pain.",
            "ठंडा पानी या दही, अगर आप लेते हैं।",
            "आज और मिर्च न खाएँ। बाद में सादा खाना।",
            "बैठे रहें। तुरंत चित न लेटें।",
            "खून या तेज़ दर्द हो तो डॉक्टर।"),
        n("knee|ghutna|घुटने|घुटना", "knee pain", "घुटने का दर्द",
            "Sit with the knee a little straight. Do not squat or climb stairs if it hurts.",
            "A cloth with ice wrapped, a few minutes, can help if the knee is hot. Warm cloth if it is stiff and not hot.",
            "Take only joint medicine your doctor already gave you.",
            "See a doctor if you cannot bear weight, the knee locks, or it swells a lot.",
            "घटना थोड़ा सीधा रखकर बैठें। दर्द हो तो बैठक या सीढ़ी न करें।",
            "गरम सूजन हो तो कपड़े में बर्फ कुछ मिनट। अकड़न हो तो गुनगुना कपड़ा।",
            "केवल डॉक्टर वाली जोड़ों की दवाई।",
            "वजन न सहे, अटके, या बहुत सूजे तो डॉक्टर।"),
        n("back pain|kamar|कमर दर्द|पीठ दर्द", "back pain", "कमर दर्द",
            "Lie on your side with a pillow between the knees, or on the back with a pillow under the knees.",
            "A warm cloth on the sore spot can help. Stand up slowly.",
            "Do not lift heavy bags. Take only pain medicine your doctor already gave you.",
            "Call a doctor if one leg is numb, you cannot control urine, or pain follows a fall.",
            "करवट, घुटनों के बीच तकिया; या पीठ के बल, घुटनों के नीचे तकिया।",
            "गुनगुना कपड़ा। धीरे उठें।",
            "भारी बैग न उठाएँ। केवल डॉक्टर वाली दर्द की दवाई।",
            "टांग सुन्न, पेशाब न संभले, या गिरने के बाद हो तो डॉक्टर।"),
        n("neck pain|gardan dard|गर्दन दर्द", "neck pain", "गर्दन दर्द",
            "Sit with the back supported. A warm cloth on the neck.",
            "Do not suddenly twist the neck. Use a thin pillow tonight.",
            "Look at the phone less. Take only medicine your doctor already gave you.",
            "Call a doctor if the arms are numb, you hit the head, or pain is very strong.",
            "पीठ टिकाकर बैठें। गर्दन पर गुनगुना कपड़ा।",
            "अचानक गर्दन न मरोड़ें। रात को पतला तकिया।",
            "फ़ोन कम देखें। केवल डॉक्टर वाली दवाई।",
            "बाजू सुन्न, सिर लगी हो, या बहुत तेज़ दर्द हो तो डॉक्टर।"),
        n("shoulder|kandha|कंधे दर्द|कंधा", "shoulder pain", "कंधे का दर्द",
            "Rest the arm on a pillow. Do not lift that arm high.",
            "A warm cloth can ease stiffness.",
            "Take only pain medicine your doctor already gave you.",
            "See a doctor if you cannot lift the arm at all or it followed a fall.",
            "बाजू तकिये पर रखें। ऊँचा न उठाएँ।",
            "अकड़न पर गुनगुना कपड़ा।",
            "केवल डॉक्टर वाली दर्द की दवाई।",
            "बिल्कुल न उठे या गिरने के बाद हो तो डॉक्टर।"),
        n("hip pain|koolhe|कूल्हे दर्द|कमर नीचे", "hip pain", "कूल्हे का दर्द",
            "Sit in a firm chair. Stand up slowly. A warm cloth can help.",
            "Do not cross the legs if it hurts.",
            "Take only medicine your doctor already gave you.",
            "See a doctor after a fall, or if you cannot bear weight.",
            "मज़बूत कुर्सी पर बैठें। धीरे उठें। गुनगुना कपड़ा।",
            "दर्द हो तो पैर न चढ़ाएँ।",
            "केवल डॉक्टर वाली दवाई।",
            "गिरने के बाद या वजन न सहें तो डॉक्टर।"),
        n("sciatica|sciatic|सायटिका|टांग में करंट", "sciatica", "सायटिका",
            "Lie on the side with the knees a little bent. A pillow between the knees.",
            "A warm cloth on the back. Walk short, slow steps later if you can.",
            "Do not bend and lift. Take only medicine your doctor already gave you.",
            "Call a doctor if the foot is weak or you cannot control urine.",
            "करवट, घुटने थोड़े मुड़े, बीच में तकिया।",
            "पीठ पर गुनगुना कपड़ा। बाद में धीरे थोड़ा चलें।",
            "झुककर सामान न उठाएँ। केवल डॉक्टर वाली दवाई।",
            "पैर कमज़ोर या पेशाब न संभले तो डॉक्टर।"),
        n("joint pain|gathiya|जोड़ों दर्द|गठिया", "joint pain", "जोड़ों का दर्द",
            "Rest the sore joint. A warm cloth if it is stiff, not red-hot.",
            "Move it slowly after rest. Do not force it.",
            "Take only joint medicine your doctor already gave you.",
            "See a doctor if one joint is very hot, red, or you cannot move it.",
            "जोड़ को आराम। अकड़न हो तो गुनगुना कपड़ा, लाल-गरम हो तो नहीं।",
            "आराम के बाद धीरे हिलाएँ। ज़ोर न करें।",
            "केवल डॉक्टर वाली जोड़ों की दवाई।",
            "एक जोड़ बहुत गरम-लाल हो या न हिले तो डॉक्टर।"),
        n("gout|gathiya pair|अंगूठे में दर्द|gouty", "gout pain", "गाउट जैसा दर्द",
            "Rest the foot. Raise it a little. A cool cloth can help if it is hot.",
            "Drink water. Skip alcohol and heavy meat if those are in your meals.",
            "Take only the gout medicine your doctor already gave you. Do not start a new pain tablet on your own.",
            "See a doctor if the joint is very hot or you have fever too.",
            "पैर आराम, थोड़ा ऊँचा। गरम हो तो ठंडा कपड़ा।",
            "पानी पिएँ। शराब और भारी मांस छोड़ें अगर खाते हैं।",
            "केवल डॉक्टर वाली गाउट की दवाई। नई दर्द की गोली खुद से न लें।",
            "जोड़ बहुत गरम या साथ बुखार हो तो डॉक्टर।"),
        n("arthritis|arthrit|आर्थराइटिस", "arthritis flare", "गठिया बढ़ना",
            "Rest the joint. Warm cloth for stiffness. Slow movement after rest.",
            "Use the walking stick if you have one.",
            "Take only the arthritis medicine your doctor already gave you.",
            "See a doctor if swelling grows fast or you have fever.",
            "जोड़ आराम। अकड़न पर गुनगुना कपड़ा। बाद में धीरे हिलाएँ।",
            "छड़ी हो तो इस्तेमाल करें।",
            "केवल डॉक्टर वाली गठिया की दवाई।",
            "सूजन तेज़ी से बढ़े या बुखार हो तो डॉक्टर।"),
        n("cramp|tain|ainthan pair|पिंडली|cramp in", "leg cramp", "पिंडली में ऐंठन",
            "Straighten the leg and pull the toes toward you, slowly.",
            "Stand and put the heel down if you can. A warm cloth after it eases.",
            "Sip water. Tell family if cramps come every night.",
            "Call a doctor if the calf is swollen, hot, or the pain does not ease.",
            "टांग सीधी करें, अंगुलियाँ धीरे अपनी ओर खींचें।",
            "हो सके तो एड़ी रखकर खड़े हों। बाद में गुनगुना कपड़ा।",
            "पानी पिएँ। हर रात हो तो परिवार को बताएँ।",
            "पिंडली सूजी-गरम हो या दर्द न घटे तो डॉक्टर।"),
        n("swollen (feet|foot|ankles)|pair sooj|पैर सूज|टखने सूज", "swollen feet", "पैर सूजना",
            "Sit and raise the feet on a stool. Loose shoes or none at home.",
            "Do not add extra salt. Walk a little later if you can.",
            "Call a doctor if one leg only is swollen, you are short of breath, or this is new.",
            "Do not massage hard.",
            "पैर स्टूल पर ऊँचे करके बैठें। घर में ढीले जूते।",
            "अतिरिक्त नमक न लें। बाद में थोड़ा चलें।",
            "एक ही पैर सूजे, साँस फूल, या नया हो तो डॉक्टर।",
            "ज़ोर से मसाज न करें।"),
        n("sprain|moot|मोच", "sprain", "मोच",
            "Rest. Raise the part. A cloth-wrapped cool pack for a few minutes.",
            "Do not walk far on a sprained ankle.",
            "A soft wrap if you have one, not too tight.",
            "See a doctor if you cannot stand on it or it looks crooked.",
            "आराम। हिस्सा ऊँचा। कपड़े में ठंड कुछ मिनट।",
            "मोच वाले टखने पर दूर न चलें।",
            "नरम पट्टी, बहुत कसकर नहीं।",
            "खड़े न हो सकें या टेढ़ा लगे तो डॉक्टर।"),
        n("body ache|badan dard|बदन दर्द|मांसपेश", "body ache", "बदन दर्द",
            "Rest. A warm bath or warm cloth if you can do it safely.",
            "Sip water. Sleep early.",
            "Take only body-ache medicine your doctor already gave you.",
            "Call a doctor if one side is weak or the chest also hurts.",
            "आराम। सुरक्षित हो तो गुनगुना स्नान या कपड़ा।",
            "पानी पिएँ। जल्दी सोएँ।",
            "केवल डॉक्टर वाली बदन दर्द की दवाई।",
            "एक तरफ़ कमज़ोरी या सीने में दर्द हो तो डॉक्टर।"),
        n("vertigo|chakkar ghoom|चक्कर घूम| कमरा घूम", "vertigo", "घूमता चक्कर",
            "Sit or lie still. Do not turn the head quickly.",
            "Keep the eyes on one point. Ask someone to stay.",
            "Stand only when the room is steady. Hold a wall.",
            "See a doctor if this is new, you faint, or you also have ear pain or hearing change.",
            "शांत बैठें या लेटें। सिर जल्दी न घुमाएँ।",
            "एक बिंदु देखें। किसी को पास रखें।",
            "कमरा स्थिर हो तब उठें। दीवार पकड़ें।",
            "नया हो, बेहोशी, या कान/सुनना बदले तो डॉक्टर।"),
        n("dizz|giddy|chakkar|चक्कर|चकरा", "dizziness", "चक्कर",
            "Sit or lie down at once. Do not stand quickly.",
            "Sip water. Eat a little if you have not eaten and your doctor allows it.",
            "Ask someone to stay. Stand only when steady.",
            "Use SOS if you faint, the chest hurts, or speech is slurred.",
            "तुरंत बैठें या लेटें। जल्दी न उठें।",
            "पानी पिएँ। भूख हो और डॉक्टर ने मना न किया हो तो थोड़ा खाएँ।",
            "किसी को पास रखें। स्थिर लगने पर ही खड़े हों।",
            "बेहोशी, सीने में दर्द, या बोली लड़खड़ाए तो एसओएस।"),
        n("weak|kamzori|कमजोरी", "weakness", "कमजोरी",
            "Sit down. Do not walk far alone.",
            "Sip water. If you take sugar medicines, check sugar the way your doctor taught you.",
            "Tell family. Rest.",
            "Call a doctor if you shake, feel confused, or cannot stand.",
            "बैठ जाएँ। अकेले दूर न चलें।",
            "पानी पिएँ। शुगर की दवाई लेते हैं तो डॉक्टर के तरीके से शुगर देखें।",
            "परिवार को बताएँ। आराम करें।",
            "काँपना, उलझन, या खड़े न हों तो डॉक्टर।"),
        n("tired|thakan|थकान|थक गया", "tiredness", "थकान",
            "Sit or lie down. Drink water. Rest the eyes.",
            "Eat a small usual meal if it is mealtime.",
            "Do not start extra work today.",
            "Call a doctor if tiredness is sudden, you are short of breath, or it lasts many days.",
            "बैठें या लेटें। पानी पिएँ। आँखें आराम।",
            "खाने का समय हो तो थोड़ा साधारण खाना।",
            "आज अतिरिक्त काम न करें।",
            "अचानक थकान, साँस फूल, या कई दिन हो तो डॉक्टर।"),
        n("no appetite|bhook nahi|भूख नहीं|खाना नहीं लग", "no appetite", "भूख नहीं लगना",
            "Sit. Try a little of a usual soft food and water, not force a big meal.",
            "Eat at the usual time even if a few spoons.",
            "Tell family what you could eat.",
            "Call a doctor if this lasts, you lose weight, or you vomit.",
            "बैठें। थोड़ा नरम साधारण खाना और पानी, ज़बरदस्ती भरी थाली नहीं।",
            "समय पर कुछ चम्मच ही सही।",
            "परिवार को बताएँ कितना खाया।",
            "बना रहे, वजन घटे, या उल्टी हो तो डॉक्टर।"),
        n("dehydrat|pani ki kami|पानी की कमी|सूख गया", "dehydration", "पानी की कमी",
            "Sip water or ORS often, a little at a time.",
            "Sit in shade. Loosen clothes.",
            "Rest. Do not walk in the sun.",
            "Use SOS if you faint, cannot drink, or urine has stopped.",
            "थोड़ा-थोड़ा पानी या ओआरएस बार-बार।",
            "छाया में बैठें। कपड़े ढीले करें।",
            "आराम। धूप में न चलें।",
            "बेहोशी, पी न सकें, या पेशाब बंद हो तो एसओएस।"),
        n("loo |heat stroke|garmi ki|लू लग|हीट स्ट्रोक", "heat", "लू-गर्मी",
            "Move to shade or a cool room. Loosen clothes. Lie down.",
            "Sip cool water. A wet cloth on the neck and forehead.",
            "Do not go back into the sun today.",
            "Use SOS if they are confused, very hot, or not sweating.",
            "छाया या ठंडे कमरे में लेटें। कपड़े ढीले करें।",
            "ठंडा पानी पिएँ। गर्दन-माथे पर गीला कपड़ा।",
            "आज धूप में वापस न जाएँ।",
            "उलझन, बहुत गर्मी, या पसीना न आए तो एसओएस।"),
        n("sunburn|dhoop jala|धूप जल", "sunburn", "धूप से जलन",
            "Come indoors. Cool water on the skin, not ice rubbed hard.",
            "Loose cotton clothes. Sip water.",
            "Do not put toothpaste, oil, or turmeric. Do not burst blisters.",
            "See a doctor if blisters are large, you have fever, or the face is badly burnt.",
            "घर में आएँ। त्वचा पर ठंडा पानी, बर्फ न रगड़ें।",
            "ढीले सूती कपड़े। पानी पिएँ।",
            "टूथपेस्ट, तेल, हल्दी न लगाएँ। फफोले न फोड़ें।",
            "बड़े छाले, बुखार, या चेहरा जला हो तो डॉक्टर।"),
        n("ear.?ache|kaan.{0,10}dard|कान.{0,10}दर्द", "ear pain", "कान दर्द",
            "Do not sleep on that side. Do not put a stick, pin, or oil in the ear.",
            "A warm cloth on the outside of the ear can help.",
            "Do not pour a new drop unless your doctor already said so.",
            "See a doctor if pain is strong, you have fever, or fluid or blood comes out.",
            "उस तरफ़ न सोएँ। कान में कड़ी चीज़ या तेल न डालें।",
            "बाहर गुनगुना कपड़ा रख सकते हैं।",
            "नई ड्रॉप न डालें जब तक डॉक्टर ने न कहा हो।",
            "तेज़ दर्द, बुखार, या पानी/खून आए तो डॉक्टर।"),
        n("ringing ear|kaan baj|कान बज|टिनिटस", "ringing in the ear", "कान बजना",
            "Sit in a quiet room. Do not poke the ear.",
            "Avoid very loud sound today.",
            "Note if it is one ear or both.",
            "See a doctor if it is sudden, you also feel dizzy, or hearing dropped.",
            "शांत कमरे में बैठें। कान न खुरचें।",
            "आज तेज़ आवाज़ से दूर रहें।",
            "एक कान है या दोनों, याद रखें।",
            "अचानक हो, चक्कर हो, या सुनना घटे तो डॉक्टर।"),
        n("tooth|daant|दांत.{0,10}दर्द|दाँत", "toothache", "दाँत दर्द",
            "Do not chew on that side. Rinse with lukewarm water.",
            "A cool cloth on the cheek. Do not put aspirin on the gum.",
            "Do not take a new pain tablet unless your doctor already said so.",
            "See a dentist if the face swells, you have fever, or the pain does not ease.",
            "उस तरफ़ न चबाएँ। गुनगुने पानी से कुल्ला।",
            "गाल पर ठंडा कपड़ा। मसूड़े पर एस्पिरिन न रखें।",
            "नई दर्द की गोली न लें जब तक डॉक्टर ने न कहा हो।",
            "चेहरा सूजे, बुखार हो, या दर्द न घटे तो दंत चिकित्सक।"),
        n("bleeding gum|masoode|मसूड़े से खून", "bleeding gums", "मसूड़ों से खून",
            "Rinse gently with lukewarm water. Press a clean cloth on the gum.",
            "Do not brush hard today. Soft food.",
            "See a dentist if it does not stop or this happens often.",
            "Call a doctor if you also bruise easily or bleed elsewhere.",
            "गुनगुने पानी से धीरे कुल्ला। साफ़ कपड़ा दबाएँ।",
            "आज ज़ोर से ब्रश न करें। नरम खाना।",
            "न रुके या बार-बार हो तो दंत चिकित्सक।",
            "और जगह खून या आसानी से नील पड़े तो डॉक्टर।"),
        n("mouth ulcer|chhala muh|मुँह का छाला|छाला मुँह", "mouth ulcer", "मुँह का छाला",
            "Rinse with lukewarm water. Eat soft, not spicy, food.",
            "Drink through a cup, not very hot tea.",
            "Do not put a new chemical on it unless your doctor said so.",
            "See a doctor if an ulcer lasts more than two weeks or you have many.",
            "गुनगुने पानी से कुल्ला। नरम, बिना तीखा खाना।",
            "बहुत गरम चाय न पिएँ।",
            "नई दवा मुँह में न लगाएँ जब तक डॉक्टर ने न कहा हो।",
            "दो सप्ताह से ज़्यादा या बहुत छाले हों तो डॉक्टर।"),
        n("stye|anjana|अंजना|पलक फोड़ा", "stye", "पलक पर फोड़ा",
            "Do not squeeze it. A clean warm cloth on the closed eye, a few minutes.",
            "Wash hands before touching the face.",
            "Do not put a new eye cream unless your doctor said so.",
            "See a doctor if the whole eyelid swells or vision changes.",
            "दबाएँ नहीं। बंद आँख पर साफ़ गुनगुना कपड़ा कुछ मिनट।",
            "चेहरा छूने से पहले हाथ धोएँ।",
            "नई आँख की क्रीम न लगाएँ जब तक डॉक्टर ने न कहा हो।",
            "पूरी पलक सूजे या दिखना बदले तो डॉक्टर।"),
        n("red eye|aankh lal|आँख लाल|आंख लाल", "red eye", "लाल आँख",
            "Do not rub. Rinse with clean water. Rest the eyes.",
            "Use a separate towel. Wash hands.",
            "Do not put someone else’s drops in the eye.",
            "See a doctor if pain is strong, light hurts a lot, or vision is blurry.",
            "रगड़ें नहीं। साफ़ पानी से धोएँ। आँख आराम।",
            "अलग तौलिया। हाथ धोएँ।",
            "दूसरे की आँख की ड्रॉप न डालें।",
            "तेज़ दर्द, रोशनी से बहुत तकलीफ, या धुंध हो तो डॉक्टर।"),
        n("watery eye|aankh se pani|आँख से पानी", "watery eyes", "आँख से पानी",
            "Do not rub. Wipe with a clean cloth from the inner corner out.",
            "Stay out of wind and dust.",
            "Rest the eyes.",
            "See a doctor if this lasts, the eye is red and painful, or vision changes.",
            "रगड़ें नहीं। साफ़ कपड़े से अंदर से बाहर पोंछें।",
            "हवा और धूल से दूर रहें।",
            "आँखों को आराम दें।",
            "बना रहे, लाल दर्द हो, या दिखना बदले तो डॉक्टर।"),
        n("eye.{0,10}(pain|hurt|burn)|aankh.{0,8}dard|आँख.{0,8}दर्द|आंख दर्द", "eye pain", "आँख में दर्द",
            "Do not rub. Rinse with clean water. Rest out of bright light.",
            "Do not put in a new drop unless your doctor already said so.",
            "Cover loosely with a clean cloth if light hurts.",
            "See a doctor if vision is blurry, pain is strong, or something hit the eye.",
            "रगड़ें नहीं। साफ़ पानी। तेज़ रोशनी से दूर।",
            "नई ड्रॉप न डालें जब तक डॉक्टर ने न कहा हो।",
            "रोशनी दुखे तो साफ़ कपड़ा हल्का रखें।",
            "धुंध, तेज़ दर्द, या चोट लगी हो तो डॉक्टर।"),
        n("something in (the )?eye|aankh mein kuch|आँख में कुछ|कण आँख", "something in the eye", "आँख में कण",
            "Do not rub. Blink in a bowl of clean water or rinse the face.",
            "Pull the upper lid over the lower if you can.",
            "If it does not come out, see a doctor. Do not use a needle.",
            "Use SOS if a chemical or metal went in.",
            "रगड़ें नहीं। साफ़ पानी में पलकें झपकाएँ या चेहरा धोएँ।",
            "हो सके तो ऊपरी पलक निचली पर लाएँ।",
            "न निकले तो डॉक्टर। सुई न लगाएँ।",
            "केमिकल या लोहा गया हो तो एसओएस।"),
        n("nosebleed|nak se khoon|नाक से खून", "nosebleed", "नाक से खून",
            "Sit up. Lean a little forward. Pinch the soft part of the nose for 10 minutes. Breathe through the mouth.",
            "Do not tilt the head back. Do not pack dry cotton deep inside.",
            "A cool cloth on the nose bridge can help.",
            "Use SOS if it will not stop, you feel faint, or blood is very heavy.",
            "बैठें, थोड़ा आगे झुकें। नरम नाक 10 मिनट दबाएँ। मुँह से साँस।",
            "सिर पीछे न करें। सूती अंदर गहरा न ठूँसें।",
            "नाक की हड्डी पर ठंडा कपड़ा।",
            "न रुके, चक्कर आए, या बहुत खून हो तो एसओएस।"),
        n("burn|jal gaya|जल गया|जलन हाथ|जलन", "burn", "जलना",
            "Run cool clean water for about 10 minutes. Do not rub ice.",
            "Do not burst blisters. Take off tight rings or cloth if you can.",
            "Do not put toothpaste, oil, or turmeric on it.",
            "See a doctor if the burn is large, on the face or hand, or the blister is big.",
            "ठंडा साफ़ पानी करीब 10 मिनट। बर्फ न रगड़ें।",
            "फफोले न फोड़ें। तंग अंगूठी-कपड़ा निकालें।",
            "टूथपेस्ट, तेल, हल्दी न लगाएँ।",
            "बड़ा जला, चेहरा/हाथ, या बड़ा छाला हो तो डॉक्टर।"),
        n("cut |kat gaya|कट गया|घाव|wound", "cut", "कट-घाव",
            "Press a clean cloth until bleeding slows. Wash with clean water if dirt is in it.",
            "Cover with a clean cloth. Raise the part if you can.",
            "Do not put mud, oil, or turmeric.",
            "See a doctor if it is deep, will not stop bleeding, or you have not had a tetanus shot as advised.",
            "साफ़ कपड़े से दबाएँ। मिट्टी हो तो साफ़ पानी से धोएँ।",
            "साफ़ कपड़ा बाँधें। हो सके तो ऊँचा रखें।",
            "मिट्टी, तेल, हल्दी न लगाएँ।",
            "गहरा हो, खून न रुके, या टिटनेस की बात डॉक्टर से करें।"),
        n("bruise|neel |नील पड़ा", "bruise", "नील",
            "Rest the part. A cloth-wrapped cool pack for a few minutes.",
            "Raise it if you can. Do not massage hard.",
            "See a doctor if bruises appear without a knock, or a joint swells a lot.",
            "Call a doctor if you also bleed from gums or the stool is black.",
            "आराम। कपड़े में ठंड कुछ मिनट।",
            "हो सके तो ऊँचा रखें। ज़ोर से मसाज न करें।",
            "बिना चोट कई नील या जोड़ बहुत सूजे तो डॉक्टर।",
            "मसूड़ों से खून या काला मल हो तो डॉक्टर।"),
        n("fell|fallen|fall down|gir gay|गिर गया|गिर गई|गिर", "after a fall", "गिरने के बाद",
            "Stay still a moment. Check the head, neck, and hip.",
            "If you can, roll to your side, then sit up slowly. Hold a chair.",
            "If you cannot get up, call out or use SOS.",
            "See a doctor if you hit your head or cannot bear weight.",
            "एक पल रुकें। सिर, गर्दन, कूल्हा देखें।",
            "करवट, फिर धीरे बैठें। कुर्सी पकड़ें।",
            "उठ न पाएँ तो आवाज़ दें या एसओएस।",
            "सिर लगा हो या वजन न सहें तो डॉक्टर।"),
        n("\\brash\\b|kharish|खुजली दाने|दाद ", "rash", "दाने-खुजली",
            "Do not scratch. Wear loose cotton clothes. Wash with clean water and keep dry.",
            "Do not put on a new cream unless your doctor already said so.",
            "Keep nails short.",
            "Call a doctor if it spreads fast, you have fever, or breathing is hard.",
            "खरोंचें नहीं। ढीले सूती कपड़े। साफ़ पानी, सुखाकर रखें।",
            "नई क्रीम न लगाएँ जब तक डॉक्टर ने न कहा हो।",
            "नाखून छोटे रखें।",
            "तेज़ी से फैले, बुखार, या साँस कठिन हो तो डॉक्टर।"),
        n("\\bitch|khujli|खुजली", "itch", "खुजली",
            "Do not scratch. Cool clean water on the skin. Loose clothes.",
            "Keep the area dry. Do not put a new powder or cream unless your doctor said so.",
            "Tell family if it is all over the body.",
            "Call a doctor if you also have fever, swelling of the face, or hard breathing.",
            "खरोंचें नहीं। ठंडा साफ़ पानी। ढीले कपड़े।",
            "सुखा रखें। नई पाउडर-क्रीम न लगाएँ जब तक डॉक्टर ने न कहा हो।",
            "पूरे बदन हो तो परिवार को बताएँ।",
            "बुखार, चेहरा सूजे, या साँस कठिन हो तो डॉक्टर।"),
        n("insect bite|machhar|मच्छर|कीट काट|bee sting|मधुमक्खी", "insect bite", "कीट का काटना",
            "Do not scratch. A cool cloth on the spot.",
            "If a sting is visible at the surface, scrape it sideways; do not squeeze.",
            "Sit still if you feel dizzy.",
            "Use SOS if the face or tongue swells or breathing is hard.",
            "खरोंचें नहीं। ठंडा कपड़ा।",
            "डंक दिखे तो किनारे से सरकाएँ, न दबाएँ।",
            "चक्कर आए तो बैठे रहें।",
            "चेहरा/जीभ सूजे या साँस कठिन हो तो एसओएस।"),
        n("hives|pitti|पित्ती|urticaria", "hives", "पित्ती",
            "Do not scratch. Loose clothes. A cool cloth.",
            "Sit. Note if a new food or medicine was taken.",
            "Take only an allergy tablet your doctor already gave you, as they told you.",
            "Use SOS if lips, tongue, or breathing change.",
            "खरोंचें नहीं। ढीले कपड़े। ठंडा कपड़ा।",
            "बैठें। नया खाना या दवाई याद करें।",
            "केवल डॉक्टर वाली एलर्जी की गोली, जैसा उन्होंने कहा।",
            "होंठ, जीभ, या साँस बदले तो एसओएस।"),
        n("dry skin|sukhi twacha|सूखी त्वचा", "dry skin", "सूखी त्वचा",
            "Short lukewarm bath, not hot. Pat dry. Use the moisturiser your doctor or you already use.",
            "Loose cotton clothes. Drink water.",
            "Do not scratch until it bleeds.",
            "See a doctor if the skin cracks and weeps or looks infected.",
            "छोटा गुनगुना स्नान, बहुत गरम नहीं। थप-थप सुखाएँ। अपनी वाली क्रीम।",
            "ढीले सूती कपड़े। पानी पिएँ।",
            "खून आने तक न खरोंचें।",
            "फटे और पानी निकले या संक्रमण लगे तो डॉक्टर।"),
        n("cracked heel|fati edi|फटी एड़ी", "cracked heels", "फटी एड़ी",
            "Wash, pat dry. Use the cream you already use. Soft cotton socks.",
            "Do not cut deep skin with a blade.",
            "Wear closed soft shoes, not open slippers on long walks.",
            "See a doctor if there is redness, pus, or you have diabetes.",
            "धोएँ, सुखाएँ। अपनी क्रीम। नरम मोज़े।",
            "ब्लेड से गहरा न काटें।",
            "लंबी सैर पर खुली चप्पल की जगह नरम जूते।",
            "लालिमा, मवाद, या शुगर हो तो डॉक्टर।"),
        n("boil|phoda|फोड़ा|फुंसी बड़ा", "boil", "फोड़ा",
            "Do not squeeze. A clean warm cloth a few times a day.",
            "Keep it covered with a clean cloth. Wash hands after touching.",
            "Do not put a new ointment unless your doctor said so.",
            "See a doctor if it is on the face, very large, or you have fever.",
            "दबाएँ नहीं। दिन में कुछ बार साफ़ गुनगुना कपड़ा।",
            "साफ़ कपड़ा ढकें। छूने के बाद हाथ धोएँ।",
            "नई मरहम न लगाएँ जब तक डॉक्टर ने न कहा हो।",
            "चेहरे पर हो, बहुत बड़ा हो, या बुखार हो तो डॉक्टर।"),
        n("blister|chhala|छाला पैर", "blister", "छाला",
            "Do not burst it. Clean around it. Soft covering if it rubs.",
            "Change to looser shoes or socks.",
            "If it bursts, wash, keep clean and dry.",
            "See a doctor if it is large, on the foot and you have diabetes, or it looks infected.",
            "फोड़ें नहीं। आसपास साफ़ रखें। रगड़े तो नरम ढकें।",
            "ढीले जूते या मोज़े।",
            "फूट जाए तो धोएँ, साफ़-सूखा रखें।",
            "बड़ा हो, शुगर हो, या संक्रमण लगे तो डॉक्टर।"),
        n("splinter|kanta ghus|काँटा धँस|कांटा", "splinter", "काँटा धँसना",
            "Wash. If the tip is out, pull with clean tweezers along the line it went in.",
            "If it is deep, leave it and see a clinic. Do not dig with a needle at home.",
            "Press a clean cloth if it bleeds.",
            "See a doctor if it is glass, metal deep, or redness spreads.",
            "धोएँ। नोक बाहर हो तो साफ़ चिमटी से उसी दिशा में निकालें।",
            " गहरा हो तो घर में सुई न चलाएँ, क्लिनिक जाएँ।",
            "खून हो तो साफ़ कपड़ा दबाएँ।",
            "काँच, गहरा लोहा, या लालिमा फैले तो डॉक्टर।"),
        n("insomnia|neend nahi|नींद नहीं|सो नहीं", "cannot sleep", "नींद न आना",
            "Sit up a while. Dim the lights. No tea or coffee now.",
            "A cup of warm milk only if you already drink it and it sits well.",
            "Do not take a new sleeping tablet unless your doctor already gave you one for this.",
            "Tell your doctor if this lasts many nights or you feel very low.",
            "कुछ देर बैठें। रोशनी कम। अब चाय-कॉफ़ी न लें।",
            "गुनगुना दूध तभी अगर आप पहले से लेते हैं और पचता है।",
            "नई नींद की गोली न लें जब तक डॉक्टर ने इसी के लिए न दी हो।",
            "कई रात या मन बहुत उदास हो तो डॉक्टर को बताएँ।"),
        n("anxious|ghabra|घबराहट|बेचैन", "anxiety", "घबराहट",
            "Sit. Feel your feet on the floor. Breathe in slowly, out slowly, a few times.",
            "Tell someone nearby. Sip water.",
            "Do not take a new calming tablet on your own.",
            "Call a doctor or use SOS if the chest hurts, you cannot breathe, or you feel you might faint.",
            "बैठें। पैर ज़मीन पर। धीरे साँस अंदर-बाहर कुछ बार।",
            "पास वाले को बताएँ। पानी पिएँ।",
            "नई शांत करने की गोली खुद से न लें।",
            "सीने में दर्द, साँस न आए, या बेहोशी लगे तो डॉक्टर या एसओएस।"),
        n("sad|udaas|उदास|रो रहा|अकेला", "feeling low", "उदासी",
            "Sit with someone if you can. Drink water. Eat a little if you have skipped meals.",
            "Tell family how you feel. Step to a window or a short walk if safe.",
            "This is not a medicine card. Stay with people you trust.",
            "If you feel unsafe or want to harm yourself, tell family and use SOS or local emergency services.",
            "हो सके तो किसी के साथ बैठें। पानी पिएँ। खाना छूटा हो तो थोड़ा खाएँ।",
            "परिवार को बताएँ। सुरक्षित हो तो खिड़की या थोड़ी सैर।",
            "यह दवाई का कार्ड नहीं। भरोसे वाले लोगों के पास रहें।",
            "अपने को नुकसान का विचार आए तो परिवार को बताएँ और एसओएस या आपातकालीन सेवा।"),
        n("hiccup|hidki|हिचकी", "hiccups", "हिचकी",
            "Sit up. Sip cold water slowly. Hold your breath a short moment if it feels easy.",
            "Do not scare someone on purpose. Avoid very hot or fizzy drinks.",
            "Rest. It often eases on its own.",
            "Call a doctor if hiccups last many hours or you cannot eat or sleep.",
            "बैठें। ठंडा पानी धीरे पिएँ। आसान लगे तो साँस थोड़ी रोकें।",
            "डराएँ नहीं। बहुत गरम या ठंडा गैस वाला पेय न लें।",
            "आराम करें। अक्सर अपने आप रुकती है।",
            "कई घंटे चले या खाना-नींद न हो तो डॉक्टर।"),
        n("urine burn|peshab jalan|पेशाब में जलन|urine pain", "burning urine", "पेशाब में जलन",
            "Drink water through the day if your doctor allows fluids.",
            "Do not hold urine. Wash front to back with clean water.",
            "Do not take a leftover antibiotic on your own.",
            "See a doctor if there is fever, back pain, blood, or you cannot pass urine.",
            "डॉक्टर ने मना न किया हो तो दिन भर पानी पिएँ।",
            "पेशाब रोकें नहीं। साफ़ पानी से आगे से पीछे धोएँ।",
            "बची एंटीबायोटिक खुद से न लें।",
            "बुखार, कमर दर्द, खून, या पेशाब न आए तो डॉक्टर।"),
        n("frequent urine|baar baar peshab|बार बार पेशाब", "frequent urine", "बार-बार पेशाब",
            "Sip water as usual, not all at once. Note how often this started.",
            "Wear easy clothes. Keep a path to the toilet clear.",
            "If you take sugar or water tablets, do not change the dose on your own.",
            "See a doctor if this is new, you have fever, or you also feel very thirsty.",
            "पानी धीरे पिएँ, एक साथ नहीं। कब से बढ़ा लिखें।",
            "आसान कपड़े। शौचालय का रास्ता साफ़ रखें।",
            "शुगर या पानी की गोली की मात्रा खुद न बदलें।",
            "नया हो, बुखार हो, या बहुत प्यास लगे तो डॉक्टर।"),
        n("cannot (pass )?urine|peshab nahi|पेशाब नहीं आ", "cannot pass urine", "पेशाब न आना",
            "Sit or stand in the way that usually works. Do not strain hard. Run a tap nearby.",
            "This needs a doctor the same day if nothing comes out.",
            "Do not take leftover tablets for this on your own.",
            "Use SOS if the belly is very full and painful.",
            "जिस तरह आता है बैठें या खड़े हों। ज़ोर न लगाएँ। पास नल चलाएँ।",
            "कुछ न आए तो उसी दिन डॉक्टर।",
            "बची गोली खुद से न लें।",
            "पेट बहुत भरा और दर्द हो तो एसओएस।"),
        n("blood in urine|peshab mein khoon|पेशाब में खून", "blood in urine", "पेशाब में खून",
            "Drink water if your doctor allows. Rest.",
            "See a doctor the same day. Take a sample if they ask later.",
            "Do not ignore even a little pink colour.",
            "Use SOS if you cannot pass urine or pain is severe.",
            "डॉक्टर ने कहा हो तो पानी पिएँ। आराम करें।",
            "उसी दिन डॉक्टर। बाद में कहें तो नमूना रखें।",
            "थोड़ा गुलाबी भी न छोड़ें।",
            "पेशाब न आए या दर्द तेज़ हो तो एसओएस।"),
        n("thirst|bahut pyaas|बहुत प्यास", "great thirst", "बहुत प्यास",
            "Sip water. Rest in shade.",
            "If you have diabetes, check sugar the way your doctor taught you.",
            "Do not drink only sugary soda.",
            "Call a doctor if thirst is sudden with frequent urine, vomiting, or confusion.",
            "पानी धीरे पिएँ। छाया में आराम।",
            "शुगर है तो डॉक्टर के तरीके से जाँचें।",
            "केवल मीठा सोडा न पिएँ।",
            "अचानक प्यास, बार-बार पेशाब, उल्टी, या उलझन हो तो डॉक्टर।"),
        n("night sweat|raat pasina|रात पसीना", "night sweats", "रात को पसीना",
            "Change to a dry cloth. Sip water. A light sheet, not a heavy quilt.",
            "Note if you also have fever or cough.",
            "Tell your doctor if this happens many nights.",
            "Call sooner if you also lose weight or cough blood.",
            "सूखा कपड़ा पहनें। पानी पिएँ। हल्की चादर, भारी रजाई नहीं।",
            "साथ बुखार या खाँसी है तो याद रखें।",
            "कई रात हो तो डॉक्टर को बताएँ।",
            "वजन घटे या खाँसी में खून हो तो जल्दी बताएँ।"),
        n("diabetes foot|sugar pair ghav|शुगर का घाव|पैर का घाव शुगर", "foot wound with diabetes", "शुगर में पैर का घाव",
            "Sit. Raise the foot. Do not walk barefoot. Do not put oil, turmeric, or heat on it.",
            "Wash as your doctor already taught you, or rinse with clean water and pat dry.",
            "Cover with a clean cloth. See the doctor the same day.",
            "Use SOS if the foot is very red, you have fever, or a dark patch grows.",
            "बैठें। पैर ऊँचा। नंगे पैर न चलें। तेल, हल्दी, गर्मी न लगाएँ।",
            "डॉक्टर के बताए अनुसार धोएँ, या साफ़ पानी और सुखाएँ।",
            "साफ़ कपड़ा। उसी दिन डॉक्टर।",
            "बहुत लाल, बुखार, या काला धब्बा बढ़े तो एसओएस।"),
        n("bed sore|bedsore|बिस्तर घाव|दबाव घाव", "pressure sore", "बिस्तर का घाव",
            "Do not lie on that spot. Change position often, with help.",
            "Keep the skin clean and dry. Soft cloth, no tight sheet wrinkles.",
            "Do not put oil or home paste on an open sore.",
            "A nurse or doctor should see any open bed sore.",
            "उस जगह न लेटें। मदद से बार-बार करवट।",
            "त्वचा साफ़-सूखी। नरम कपड़ा, चादर की सिलवट न रहे।",
            "खुले घाव पर तेल या लेप न लगाएँ।",
            "खुला बिस्तर घाव डॉक्टर या नर्स को दिखाएँ।"),
        n("numb (hand|foot|feet|arm|leg)|सुन्न|झनझनाहट", "numbness", "सुन्नपन",
            "Sit. Shake the part gently. Change position.",
            "Do not put heat on a numb part. You may burn it without feeling.",
            "Note if it is one side of the body.",
            "Use SOS if the face also droops, speech is slurred, or one whole side is weak.",
            "बैठें। धीरे हिलाएँ। मुद्रा बदलें।",
            "सुन्न जगह पर गर्मी न लगाएँ, जलन पता नहीं चलेगी।",
            "एक तरफ़ है या नहीं, याद रखें।",
            "मुँह टेढ़ा, बोली लड़खड़ाए, या पूरी तरफ़ कमज़ोर हो तो एसओएस।"),
        n("tremor|kaanp|काँप रहा हाथ|हाथ काँप", "shaking hands", "हाथ काँपना",
            "Sit. Rest the hands on a table. Sip water.",
            "If you take sugar medicines, check sugar the way your doctor taught you.",
            "Do not take a new tablet for shaking on your own.",
            "Call a doctor if this is new, strong, or you also feel faint.",
            "बैठें। हाथ मेज़ पर रखें। पानी पिएँ।",
            "शुगर की दवाई लेते हैं तो डॉक्टर के तरीके से शुगर देखें।",
            "काँपने की नई गोली खुद से न लें।",
            "नया, तेज़, या चक्कर हो तो डॉक्टर।"),
        n("confus|uljhan dimag|उलझन|समझ नहीं", "confusion", "उलझन",
            "Sit with them. Speak slowly. Do not leave them alone.",
            "If they take sugar or BP medicines, check those the way the doctor taught, if you can.",
            "Use SOS if this started suddenly, they are not themselves, or they cannot stay awake.",
            "A doctor should see new confusion the same day.",
            "साथ बैठें। धीरे बोलें। अकेले न छोड़ें।",
            "शुगर या बीपी की दवाई हो तो डॉक्टर के तरीके से देखें।",
            "अचानक बदले, अपने जैसे न लगें, या जाग न सकें तो एसओएस।",
            "नई उलझन उसी दिन डॉक्टर को दिखाएँ।"),
        n("memory|bhool|भूल रहा|याद नहीं", "forgetfulness", "भूलना",
            "Sit. Keep glasses, keys, and medicines in one place. Write the day on a paper.",
            "Tell family. Do not change medicines on your own.",
            "Eat and drink at usual times.",
            "See a doctor if this is new or they get lost or leave the stove on.",
            "बैठें। चश्मा, चाबी, दवाई एक जगह। दिन कागज पर लिखें।",
            "परिवार को बताएँ। दवाई खुद न बदलें।",
            "खाने-पानी का समय रखें।",
            "नया हो, रास्ता भूलें, या चूल्हा खुला छोड़ें तो डॉक्टर।"),
        n("hiccup", "hiccups", "हिचकी",
            "Sit up. Sip cold water slowly.",
            "Hold the breath a short moment if it feels easy. Avoid fizzy drinks.",
            "Rest. It often eases on its own.",
            "Call a doctor if it lasts many hours.",
            "बैठें। ठंडा पानी धीरे पिएँ।",
            "आसान लगे तो साँस थोड़ी रोकें। गैस वाला पेय न लें।",
            "आराम करें। अक्सर रुक जाती है।",
            "कई घंटे चले तो डॉक्टर।"),
        n("covid|corona|कोविड|कोरोना", "covid-like illness", "कोविड जैसी तबीयत",
            "Rest in a separate room if you can. Wear a cloth on the face when near others.",
            "Sip water. Check fever. Open a window.",
            "Take only fever medicine your doctor already gave you.",
            "Use SOS if breathing is hard or lips look blue. Call a doctor if this lasts.",
            "हो सके तो अलग कमरे में आराम। दूसरों के पास कपड़ा पहनें।",
            "पानी पिएँ। बुखार देखें। खिड़की खोलें।",
            "केवल डॉक्टर वाली बुखार की दवाई।",
            "साँस कठिन या होंठ नीले तो एसओएस। बना रहे तो डॉक्टर।"),
        n("long cough|purani khansi|पुरानी खाँसी|कई हफ्ते खाँसी", "long cough", "पुरानी खाँसी",
            "Sit up to cough. Sip warm water. Spit into a cloth.",
            "Stay away from smoke.",
            "Do not start a new syrup on your own.",
            "See a doctor if a cough lasts weeks, you lose weight, or there is blood.",
            "बैठकर खाँसें। गुनगुना पानी। कपड़े में थूकें।",
            "धुआँ से दूर रहें।",
            "नई सिरप खुद से न शुरू करें।",
            "हफ्तों खाँसी, वजन घटना, या खून हो तो डॉक्टर।"),
        n("hearing (drop|lost|gone)|sunai nahi|सुनई नहीं|कान बंद सुनना", "hearing dropped", "सुनना कम होना",
            "Sit in a quiet room. Do not poke the ear or pour oil.",
            "Speak facing the person. Write if needed.",
            "See a doctor the same day if hearing dropped suddenly in one ear.",
            "Call sooner if you also feel dizzy or the face is weak.",
            "शांत कमरे में बैठें। कान न खुरचें, तेल न डालें।",
            "सामने मुँह करके बोलें। ज़रूरत हो तो लिखें।",
            "एक कान अचानक कम सुने तो उसी दिन डॉक्टर।",
            "चक्कर या चेहरा कमज़ोर हो तो जल्दी जाएँ।"),
        n("jaw pain|jabde|जबड़े दर्द", "jaw pain", "जबड़े का दर्द",
            "Eat soft food. Do not chew gum. A warm cloth on the jaw.",
            "Open the mouth slowly. Do not force a wide yawn.",
            "Take only pain medicine your doctor already gave you.",
            "Call a doctor if the chest also hurts, or the jaw will not close.",
            "नरम खाना। चूइंगम न चबाएँ। जबड़े पर गुनगुना कपड़ा।",
            "मुँह धीरे खोलें। ज़ोर से जम्हाई न लें।",
            "केवल डॉक्टर वाली दर्द की दवाई।",
            "साथ में सीने में दर्द हो या जबड़ा बंद न हो तो डॉक्टर।"),
        n("hernia|hern|हर्निया|नाभि फूल", "hernia", "हर्निया",
            "Lie down and rest. Do not lift or cough hard if you can help it.",
            "Support the area with a hand when you cough.",
            "Do not push the bulge in if it is painful.",
            "Use SOS if the bulge is very painful, hard, or you vomit.",
            "लेटकर आराम। भारी सामान न उठाएँ।",
            "खाँसते समय हाथ से सहारा दें।",
            "दर्द हो तो फूलन को अंदर न धकेलें।",
            "बहुत दर्द, सख्त, या उल्टी हो तो एसओएस।"),
        n("night urine|raat ko peshab|रात को पेशाब|सोते पेशाब", "urine at night", "रात को पेशाब",
            "Sip less water in the last two hours before bed, unless a doctor said to drink at night.",
            "Keep a clear path and a light to the toilet. Sit a moment before you stand.",
            "Do not change water or sugar tablets on your own.",
            "Tell your doctor if this is new or you rush and fall.",
            "सोने से दो घंटे पहले कम पानी, जब तक डॉक्टर ने रात को पीने को न कहा हो।",
            "शौचालय का रास्ता साफ़, रोशनी। उठने से पहले बैठें।",
            "पानी या शुगर की गोली खुद न बदलें।",
            "नया हो या भागकर गिरें तो डॉक्टर को बताएँ।"),
        n("incontinence|peshab nikal|पेशाब निकल|कपड़े गीले", "urine leak", "पेशाब रिसना",
            "Change to a dry cloth. Wash the skin and pat dry.",
            "Keep a commode or urinal nearby if you have one.",
            "Do not stop drinking all day. Sip through the day.",
            "Tell your doctor. This has a cause they can look at.",
            "सूखा कपड़ा। त्वचा धोकर सुखाएँ।",
            "कमोड या बोतल पास रखें अगर है।",
            "पूरा दिन पानी बंद न करें। धीरे-धीरे पिएँ।",
            "डॉक्टर को बताएँ। कारण देखा जा सकता है।"),
        n("\\bpale\\b|peela pad|पीला पड़|सफ़ेद पड़", "looking pale", "पीला या फीका दिखना",
            "Sit or lie down. Sip water. Rest.",
            "Eat a usual meal if you can keep it down.",
            "Tell family. Do not start iron tablets on your own.",
            "See a doctor if this is new, you faint, or the stool is black.",
            "बैठें या लेटें। पानी पिएँ। आराम।",
            "रुकता हो तो साधारण खाना लें।",
            "परिवार को बताएँ। आयरन की गोली खुद न शुरू करें।",
            "नया हो, बेहोशी, या काला मल हो तो डॉक्टर।"),
        n("yellow (eye|skin)|peeli aankh|पीली आँख|पीलिया", "yellow eyes", "पीली आँख",
            "Rest. Sip water. Do not take leftover tablets for this.",
            "Skip oily food today.",
            "See a doctor the same day.",
            "Use SOS if you are very sleepy or vomit a lot.",
            "आराम। पानी पिएँ। बची गोली न लें।",
            "आज तैलीय खाना न खाएँ।",
            "उसी दिन डॉक्टर।",
            "बहुत नींद या ज़्यादा उल्टी हो तो एसओएस।"),
        n("scalp itch|sir khuj|सिर खुज|खुजली सिर", "itchy scalp", "सिर में खुजली",
            "Do not scratch hard. Wash with the mild shampoo you already use.",
            "Keep nails short. A cool cloth on the scalp can help.",
            "Do not put oil if the skin is broken.",
            "See a doctor if there are sores, fever, or hair comes out in patches.",
            "ज़ोर से न खरोंचें। अपनी हल्की शैंपू से धोएँ।",
            "नाखून छोटे। ठंडा कपड़ा रख सकते हैं।",
            "त्वचा फटी हो तो तेल न डालें।",
            "घाव, बुखार, या बाल धब्बे में झड़ें तो डॉक्टर।"),
        n("denture|dant ke set|दंत सेट|नकली दाँत", "denture sore", "दंत सेट से दर्द",
            "Take the set out. Rinse the mouth with lukewarm water. Soft food.",
            "Clean the set as you were taught. Do not sleep with a painful set if you can leave it out.",
            "Do not file it yourself.",
            "See the dentist if a sore lasts or the set will not sit.",
            "सेट निकालें। गुनगुने पानी से कुल्ला। नरम खाना।",
            "जैसा सिखाया साफ़ करें। दर्द हो तो रात को बाहर रखें।",
            "खुद से न घिसें।",
            "छाला रहे या सेट बैठे नहीं तो दंत चिकित्सक।"),
        n("tight shoes|jute kas|जूते कस|पैर दब", "tight shoes", "कसकर जूते",
            "Sit. Take the shoes off. Raise the feet.",
            "Wear softer, wider shoes. Check for a blister or red mark.",
            "If you have diabetes, look at the whole foot.",
            "See a doctor if a wound has started.",
            "बैठें। जूते उतारें। पैर ऊँचे करें।",
            "नरम चौड़े जूते। छाला या लाल निशान देखें।",
            "शुगर हो तो पूरा पैर देखें।",
            "घाव शुरू हो तो डॉक्टर।"),
        n("get up (fast|quickly)|jaldi uth|जल्दी उठ|खड़े होते चक्कर", "stood up too fast", "जल्दी उठना",
            "Sit or lie down again. Wait, then sit, then stand while holding a chair.",
            "Sip water. Do not rush to the toilet in the dark.",
            "Move the ankles before you stand.",
            "Tell your doctor if this happens often or you faint.",
            "फिर बैठें या लेटें। रुके, बैठे, कुर्सी पकड़कर खड़े हों।",
            "पानी पिएँ। अँधेरे में शौचालय न दौड़ें।",
            "उठने से पहले टखने हिलाएँ।",
            "बार-बार हो या बेहोशी हो तो डॉक्टर।"),
        n("sitting long|der baith|देर बैठ|कमर अकड़ बैठ", "stiff after sitting", "देर बैठने से अकड़न",
            "Move the feet, then stand slowly holding a chair. Walk a few steps.",
            "A warm cloth on the back or knees.",
            "Stand and stretch gently every half hour if you can.",
            "Call a doctor if one leg swells or pain is sharp.",
            "पैर हिलाएँ, कुर्सी पकड़कर धीरे उठें। कुछ कदम चलें।",
            "पीठ या घुटने पर गुनगुना कपड़ा।",
            "हो सके तो आधे घंटे में खड़े होकर धीरे तानें।",
            "एक टांग सूजे या दर्द तेज़ हो तो डॉक्टर।"),
        n("missed meal|khana chhoot|खाना छूट|भूख से चक्कर", "missed a meal", "खाना छूटना",
            "Sit. Eat a little usual food and sip water.",
            "If you take sugar medicines, check sugar the way your doctor taught you.",
            "Do not take extra tablets because a meal was late.",
            "Call a doctor if you feel faint or confused.",
            "बैठें। थोड़ा साधारण खाना और पानी।",
            "शुगर की दवाई लेते हैं तो डॉक्टर के तरीके से शुगर देखें।",
            "खाना देर से हुआ इसलिए अतिरिक्त गोली न लें।",
            "बेहोशी या उलझन हो तो डॉक्टर।"),
        n("fish bone|machli kant|मछली का काँटा|गले काँटा", "fish bone in throat", "गले में मछली का काँटा",
            "Do not force dry bread if it hurts sharply. Sip water.",
            "If you can see it and it is loose, a doctor should still check.",
            "Do not poke with a finger.",
            "See a doctor if pain stays, you drool, or breathing feels odd.",
            "तेज़ चुभे तो सूखी रोटी ज़बरदस्ती न निगलें। पानी पिएँ।",
            "दिखे और ढीला हो तो भी डॉक्टर देखें।",
            "उंगली न डालें।",
            "दर्द रहे, लार बहे, या साँस अजीब लगे तो डॉक्टर।"),
        n("something in (the )?ear|kaan mein kuch|कान में कुछ", "something in the ear", "कान में कुछ",
            "Do not poke with a pin or bud. Tilt that ear down and shake gently.",
            "Do not pour oil or water if you think it is a seed or battery.",
            "See a clinic. They have tools for this.",
            "See sooner if pain, hearing drop, or a live insect will not come out.",
            "पिन या बुड न डालें। वह कान नीचे झुकाकर धीरे हिलाएँ।",
            "बीज या बैटरी लगे तो तेल-पानी न डालें।",
            "क्लिनिक जाएँ। उनके पास औज़ार होते हैं।",
            "दर्द, सुनना घटे, या कीड़ा न निकले तो जल्दी जाएँ।"),
        n("bathroom fall|nahate gir|नहाते गिर|गीले फर्श", "fall in the bathroom", "नहाने में गिरना",
            "Stay still. Call out or use SOS if you cannot get up.",
            "If you can, sit, then crawl to a dry mat, then hold the wall.",
            "Dry the floor before the next bath. Ask family for a stool and a rail.",
            "See a doctor if you hit the head or hip.",
            "रुकें। उठ न पाएँ तो आवाज़ दें या एसओएस।",
            "बैठें, सूखी चटाई तक रेंगें, दीवार पकड़ें।",
            "अगली बार फर्श सुखाएँ। स्टूल और सहारा माँगें।",
            "सिर या कूल्हा लगा हो तो डॉक्टर।"),
        n("glasses headache|chashma dard|चश्मे से दर्द", "headache from glasses", "चश्मे से सिर दर्द",
            "Take the glasses off for a few minutes. Rest the eyes in dim light.",
            "Check they are clean and sit straight on the nose.",
            "Do not keep wearing a broken or very old pair if it hurts.",
            "See the eye doctor if this happens every day.",
            "कुछ मिनट चश्मा उतारें। कम रोशनी में आँख आराम।",
            "साफ़ हैं और नाक पर सीधे हैं, देखें।",
            "टूटा या बहुत पुराना चश्मा दर्द दे तो न पहनें।",
            "रोज़ हो तो आँख के डॉक्टर को दिखाएँ।"),
    )

    private fun u(keys: String, en: String, hi: String, e1: String, e2: String, e3: String, e4: String, h1: String, h2: String, h3: String, h4: String) =
        CareSpec(compile(keys), en, hi, true, listOf(e1, e2, e3, e4), listOf(h1, h2, h3, h4))

    private fun n(keys: String, en: String, hi: String, e1: String, e2: String, e3: String, e4: String, h1: String, h2: String, h3: String, h4: String) =
        CareSpec(compile(keys), en, hi, false, listOf(e1, e2, e3, e4), listOf(h1, h2, h3, h4))

    private fun compile(keys: String) = runCatching { Regex(keys) }.getOrElse { Regex(Regex.escape(keys)) }
}